local evolved = require("lib.evolved")

function init(self)
	local app_id = require "local.photon_app_id"
	fusion.init(app_id, "1.0")
	evolved.debug_mode(true)

	local test_entity = evolved.id()
	local test_fragment = evolved.id()

	evolved.set(test_entity, test_fragment, 123)

	print(string.format("Entity: %d, with fragment: %d, with value: %d", test_entity, test_fragment, evolved.get(test_entity, test_fragment)))
	print(fusion.STATE_DISCONNECTED)
end

function final(self)

end

function update(self, dt)

end

function late_update(self, dt)

end

function fixed_update(self, dt)

end

function on_message(self, message_id, message, sender)

end

function on_input(self, action_id, action)

end

function on_reload(self)

end
